# EMOJI REACTIONS AND STICKERS
EMOJI_REACT = [
    "🍓",  "💊",  "🦄",  "💅",  "💘",
    "💋",  "🍌",  "⚡",  "🕊️",  "❤️‍🔥",
    "🔥",  "❤️"
]

# Stickers for after /start command
START_STICKERS = [
    "CAACAgUAAxkBAAEPHVRomHVszeSnrB2qQBGNHy6BgyZAHwACvxkAAmpxyFT7N37qhVnGmzYE",
    "CAACAgUAAxkBAAEPHVVomHVsuGrU-zEa0X8i1jn_HW7XawAC-BkAArnxwVRFqeVbp2Mn_TYE",
    "CAACAgUAAxkBAAEPHVZomHVsuf3QWObxnD9mavVnmS4XPgACPhgAAqMryVT761H_MmILCjYE",
    "CAACAgUAAxkBAAEPHVdomHVs87jwVjxQjM7k37cUAwnJXQACwxYAAs2CyFRnx4YgWFPZkjYE",
    "CAACAgUAAxkBAAEPHVhomHVsnB4iVT8jr56ZtGPq98KQeQACfRgAAoQAAcBUyVgSjnENUUo2BA",
    "CAACAgUAAxkBAAEPHVlomHVsRWNXE2vkgSYrBU9K-JB9UwACoxcAAi4MyFS0w-gqFTBWQjYE",
    "CAACAgUAAxkBAAEPHVpomHVsfUZT06tR7jgqmHNJA-j5fAACpBgAAuhZyVSaY0y3w0zVLjYE",
    "CAACAgUAAxkBAAEPHVtomHVsqjujca8HBOPQpEvJY-I0WQACZRQAAhX0wFS2YntXBMU6ATYE",
    "CAACAgUAAxkBAAEPHVxomHVsw09_FKmfugTeaqTXrIOMNwACzhQAAlyLwFSL4-96tJu0STYE",
    "CAACAgUAAxkBAAEPHV1omHVsP9aNtLlGJyErPF8yEvuuawAC6RcAAj7DwFSKnv319y6jnTYE",
    "CAACAgUAAxkBAAEPHV5omHVsuz9c3bxncAXOQ6BDzhrTnwACKxwAAm4QwVRdrk0EgrotFjYE",
    "CAACAgUAAxkBAAEPHV9omHVs3df-rmdlDbJFu-MREg5RrwAC5RYAAsCewVSvwTepiO6BlTYE",
    "CAACAgUAAxkBAAEPHWBomHVshaztRlsJ2d3p6qV1TAolvgACChkAAjf9wFSqz_XgZVhTLTYE",
    "CAACAgUAAxkBAAEPHWFomHVsrjl_UqIUYgs8NUKycyXbuQAChRgAApa6wFQoEbjt-4UEUDYE",
    "CAACAgUAAxkBAAEPHWJomHVssUsAAU8BbI1lcPdQ2hJbbrwAAg4YAAI4lchULkVARTsFmjI2BA",
    "CAACAgUAAxkBAAEPHWNomHVs0wFx3n8i8r6TefoJzP_3XAACqRYAAvKvyFQiY8XErd3KFDYE",
    "CAACAgUAAxkBAAEPHWRomHVsXNHMWzXxpKxSrze5yM0kzAACRx4AAt7oyFS3n9YnyqQwCjYE",
    "CAACAgUAAxkBAAEPHWVomHVsQxKxih6IfqUeZ7aQaCXBvAACyBgAAkHPwVT8uW_J5GUHQTYE",
    "CAACAgUAAxkBAAEPHWZomHVsFSeBqaNqm5rWNu8LdszNcAACxhUAAuEtwVQi2t0gazmalDYE",
    "CAACAgUAAxkBAAEPHWdomHVsFOXCOM_DZb1VuGPlXfkY2AAC4RgAAu2CwVSxJETZ5OhUGTYE",
    "CAACAgUAAxkBAAEPHWhomHVsovXP8XqbvEjEB508DTW6VQAC2BcAAoJLwFRRhczsSdgAASg2BA",
    "CAACAgUAAxkBAAEPHWlomHVsNkxBtCovGit7bjWNEV5kTwACFhYAArQ9wFRAwzg1qA0TrTYE",
    "CAACAgUAAxkBAAEPHWpomHVs8vADDgs56H30a5uM2uNvhQACtxcAAj_QQVSXTCvC5zEIPjYE",
    "CAACAgUAAxkBAAEPHWtomHVsS466sNdxHk4lGsza3S_3yQAC9B0AAnZtQFQJYcwEnXCS6DYE",
    "CAACAgUAAxkBAAEPJzFonedaEsY_x_cVxB5i5WHRmYDfZwACdBgAAnTX8VThqO2DUegdyjYE"
]

# Sakura stickers list
SAKURA_STICKERS = [
    "CAACAgUAAxkBAAEPHYZomHbXHoaO5ZgAAWfmDG76TNdc0SgAAlMXAALQK6hV0eIcUy6BTnw2BA",
    "CAACAgUAAxkBAAEPHYdomHbXn4W5q5NZwaBXrIyH1vIQLAACthQAAvfkqVXP72iQq0BNejYE",
    "CAACAgUAAxkBAAEPHYhomHbX0HF-54Br14uoez3P0CnN1QACVhQAAiwMqFUXDEHvVKsJLTYE",
    "CAACAgUAAxkBAAEPHYlomHbXp0TzjPbKW-6vD4UZIMf1LgACmRsAAmwjsFWFJ6owU1WfgTYE",
    "CAACAgUAAxkBAAEPHYpomHbXPrYvs4bqejy5OUzzDS0oFwACVigAAr4JsVWLUPaAp8o1mDYE",
    "CAACAgUAAxkBAAEPHYtomHbXBs9aqV9_RA1ChGdZuof4zQACLxYAAsdcqVWCxB2Z-fbRGDYE",
    "CAACAgUAAxkBAAEPHYxomHbXCrWKildzkNTAchdFzbrMBQAC0xkAAupDqVUMuhU5w3qV5TYE",
    "CAACAgUAAxkBAAEPHY1omHbXE6Rdmv2m6chyBV_HH9u8XwACAhkAAjKHqVWAkaO_ky9lTzYE",
    "CAACAgUAAxkBAAEPHY5omHbXujQsxWB6OsTuyCTtOk2nlAACKxYAAhspsFV1qXoueKQAAUM2BA",
    "CAACAgUAAxkBAAEPHY9omHbX7S-80hbGGWRuLVj_wtKqygACXxkAAj60sVXgsb-vzSnt_TYE",
    "CAACAgUAAxkBAAEPHZBomHbXUxsXqH2zbJFK1GOiZzDcCwACuRUAAo2isVWykxNLWnwcYTYE",
    "CAACAgUAAxkBAAEPHZFemHbXjRN4Qa9WUbcWlRECLPp6NAACRx4AAp2SqFXcarUkpU5jzjYE",
    "CAACAgUAAxkBAAEPHZJomHbXX_4GTnA25ivpOWqe1UC66QACaBQAAu0uqFXKL-cNi_ZBJDYE",
    "CAACAgUAAxkBAAEPHZNomHbXWqwAAeuc7FCe0yCUd3DVx5YAAq8YAALcXbBVTI07io7mR2Q2BA",
    "CAACAgUAAxkBAAEPHZRomHbXxi3SDeeUOnqON0D3czFrEAACCxcAAidVsFWEt7xrqmGJxjYE",
    "CAACAgUAAxkBAAEPHZVomHbXjFFKT2Ks98KxKiTEab_NDAACEBkAAg7VqFV6tAlBFHKdPDYE",
    "CAACAgUAAxkBAAEPHZZomHbXtQ5QRjobH7M6Ys-5XO-IQQACrhQAArcDsVV3-V8JhPN1qDYE",
    "CAACAgUAAxkBAAEPHZdomHbXDL-13xEyhcVV2bAIRun90AACIBoAAquXsVX6KNOab-JSkzYE",
    "CAACAgUAAxkBAAEPHZhomHbX3mK-IPSpEpnrTVqc36bR6AACHxUAArG-qFU5OStAsdYoJTYE",
    "CAACAgUAAxkBAAEPHZlomHbXdqlqWs00NKAOToK90LgPpgACsRUAAiqIsVULIgcY4EYPbzYE",
    "CAACAgUAAxkBAAEPHZpomHbXPh9D5VSlhmSX2HEIClk92AACPxcAArtosFXxg3weTZPx5TYE",
    "CAACAgUAAxkBAAEPHZtomHbXpeFGlpeqcKIrzEsxC7PCkAACdxQAAhX8qVW1te9rkWttOzYE",
    "CAACAgUAAxkBAAEPHZxomHbXSi44c4Umy_H5JxN7BY8-8QACtRcAAtggqVVx1D8N-Hwp8TYE",
    "CAACAgUAAxkBAAEPHZ1omHbXIuMqO0K098jc3On6mCgQYAAC5hoAAnAbcFe9bbelWKStUTYE",
    "CAACAgUAAxkBAAEPHZ5omHbXVHEhhoXyZlaTtXG5YNhUwwACQhUAAqGYqFXmCuT6Lrdn-jYE",
    "CAACAgUAAxkBAAEPHZ9omHbXuHwrW1hOKXwYn9euLXxufQACHxgAAvpMqVWpxtBkEZPfPjYE",
    "CAACAgUAAxkBAAEPHaBomHbXge6qzFuLoA_ahtyIe9ptVgAC6x4AAiU7sVUROxvmQwqc0zYE",
    "CAACAgUAAxkBAAEPHaFomHbXG7wOX3wP-PNMH5uBmZqZvwACnhMAAilDsVUIsplzTkTefTYE",
    "CAACAgUAAxkBAAEPHaJomHbX3Q6jptPInCK75s45AAHneSsAArsUAAJp9qhV4C7LO05mEJM2BA",
    "CAACAgUAAxkBAAEPHaNomHbX3Q6jptPInCK75s45AAHneSsAArsUAAJp9qhV4C7LO05mEJM2BA",
    "CAACAgUAAxkBAAEPHaRomHbXia_R6dE0FmqOKe-b3CcLkgACKBkAAjb_4FVt48Cz-d5N1jYE",
    "CAACAgUAAxkBAAEPC_xoizPIGzAQCLzAjUzmRbgMYxeKbQACmRcAAnUn-VUG3_UOew4L4jYE",
    "CAACAgUAAxkBAAEPHaZomHbXCr_dCMvWOkTWL43UFUlWngACRhcAApNn8FZtvNjsiOa9nDYE",
    "CAACAgUAAxkBAAEPHadomHbXozU4tnToM5GOyR0SoYwGfQACRhYAAozAYVfKp8CwOkHT_jYE",
    "CAACAgUAAxkBAAEPHahomHbX77Pd3U0UOXwHu2GlDtisjQACVxcAAoppcVfvp-s9H4KEAzYE",
    "CAACAgUAAxkBAAEPHalomHbXG2fob7X9N-ozzyO1bDKRewACtBcAAsQ1cFcYpoovBrL4VDYE",
    "CAACAgUAAxkBAAEPHapomHbX04Yr2aCsKvkKaS8CuliIhgACrRMAAoRscFc4LHU4Cx_vCjYE",
    "CAACAgUAAxkBAAEPHatomHbXukYsQKH0Bs9SPoSmX_RhHgAC_xcAAjJPcFfbZKwhO2drjTYE",
    "CAACAgUAAxkBAAEPHaxomHbXSnidTo6q58ZX6L1_cVB3tQAClRYAAgFGaVeg-WgjAriwmzYE",
    "CAACAgUAAxkBAAEPHa1omHbXIuMqO0K098jc3On6mCgQYAAC5hoAAnAbcFe9bbelWKStUTYE",
    "CAACAgUAAxkBAAEPHa5omHbXoQe84QFvlQQlhNyKOzKUywAC9hcAArKQeVdTfgpzto8-mzYE",
    "CAACAgUAAxkBAAEPHa9omHbXPIpqHjgVWzVgmDohWt1WPAACpRUAArd2eVfJQarwwTKHazYE",
    "CAACAgUAAxkBAAEPHbBomHbXP5djg5YjJcKzaOnx_H6r_gACchUAAmVTgVe4fFRoDNGbQjYE",
    "CAACAgUAAxkBAAEPHbFomHbXEsoNl8q72uhyni6zRlDLiwACdRsAArzsgFcFaB5SZVJGmjYE",
    "CAACAgUAAxkBAAEPHbJomHbXGmztGeyRFxKICMyMeg5OYwACOxwAAqs6kVefWA1lG-qbKTYE",
    "CAACAgUAAxkBAAEPHbNomHbXOf8ffPWF1xOGw1ZVkKlH5QACUhkAAjyxmFcalZ9vPMc3BDYE",
    "CAACAgUAAxkBAAEPHbRomHbXhAT_ICabxC1mVdGeTvAacgACaxUAAhnVoFe3aPP_2ootQjYE",
    "CAACAgUAAxkBAAEPHbVomHbXawaj7Rzgrrj7Njd54dgbMAACqBYAAkhooVftJHkaW9J31zYE",
    "CAACAgUAAxkBAAEPHbZomHbXV3da8Rkgyp8RqexV84DPPwACBRsAAg4-oVctGwxN0lRv-zYE",
    "CAACAgUAAxkBAAEPHbdomHbX3l7Hm2et2D6hO5JFzFiKZgAC3BgAAiwJoFe65x8OnZGa6zYE",
    "CAACAgUAAxkBAAEPHbhomHbXA4jAd74Nlq9x6F5Ahi36ggACvRUAAp6vsVefp9E7-1xQ2zYE",
    "CAACAgUAAxkBAAEPHblomHbXUMwbfoo8TV7lXP1dgau8BAACdhcAAl7w0VdQSujQZJElODYE",
    "CAACAgUAAxkBAAEPHbpomHbXspHoRPrE8a36vnJw6diFjwACRhMAAg6w0FdJfQABKjxnTNI2BA",
    "CAACAgUAAxkBAAEPHbtomHbXZiF5VuJ0E5UZq9Ip16d1HAACsBcAAipSyFcdvir6IIjTkTYE",
    "CAACAgUAAxkBAAEPHbxomHbXfGsuWIZO7t1cxWaPAAGvGroAAhsWAAKxgclX3iuTe-84UQE2BA",
    "CAACAgUAAxkBAAEPHb1omHbXC0SYqQ0_7kDg5T01Hs1bfwACgBkAAmLbyFeRm-Xv7FhE9TYE",
    "CAACAgUAAxkBAAEPHb5omHbXLNKidlP7lGOLoL1EdDdMJwACQRgAAuLEyVfJI1470HOHnjYE"
]

# Sakura images for start command
SAKURA_IMAGES = [
    "https://ik.imagekit.io/asadofc/Images1.png",
    "https://ik.imagekit.io/asadofc/Images2.png",
    "https://ik.imagekit.io/asadofc/Images3.png",
    "https://ik.imagekit.io/asadofc/Images4.png",
    "https://ik.imagekit.io/asadofc/Images5.png",
    "https://ik.imagekit.io/asadofc/Images6.png",
    "https://ik.imagekit.io/asadofc/Images7.png",
    "https://ik.imagekit.io/asadofc/Images8.png",
    "https://ik.imagekit.io/asadofc/Images9.png",
    "https://ik.imagekit.io/asadofc/Images10.png",
    "https://ik.imagekit.io/asadofc/Images11.png",
    "https://ik.imagekit.io/asadofc/Images12.png",
    "https://ik.imagekit.io/asadofc/Images13.png",
    "https://ik.imagekit.io/asadofc/Images14.png",
    "https://ik.imagekit.io/asadofc/Images15.png",
    "https://ik.imagekit.io/asadofc/Images16.png",
    "https://ik.imagekit.io/asadofc/Images17.png",
    "https://ik.imagekit.io/asadofc/Images18.png",
    "https://ik.imagekit.io/asadofc/Images19.png",
    "https://ik.imagekit.io/asadofc/Images20.png",
    "https://ik.imagekit.io/asadofc/Images21.png",
    "https://ik.imagekit.io/asadofc/Images22.png",
    "https://ik.imagekit.io/asadofc/Images23.png",
    "https://ik.imagekit.io/asadofc/Images24.png",
    "https://ik.imagekit.io/asadofc/Images25.png",
    "https://ik.imagekit.io/asadofc/Images26.png",
    "https://ik.imagekit.io/asadofc/Images27.png",
    "https://ik.imagekit.io/asadofc/Images28.png",
    "https://ik.imagekit.io/asadofc/Images29.png",
    "https://ik.imagekit.io/asadofc/Images30.png",
    "https://ik.imagekit.io/asadofc/Images31.png",
    "https://ik.imagekit.io/asadofc/Images32.png",
    "https://ik.imagekit.io/asadofc/Images33.png",
    "https://ik.imagekit.io/asadofc/Images34.png",
    "https://ik.imagekit.io/asadofc/Images35.png",
    "https://ik.imagekit.io/asadofc/Images36.png",
    "https://ik.imagekit.io/asadofc/Images37.png",
    "https://ik.imagekit.io/asadofc/Images38.png",
    "https://ik.imagekit.io/asadofc/Images39.png",
    "https://ik.imagekit.io/asadofc/Images40.png"
]

PAYMENT_STICKERS = [
    "CAACAgUAAxkBAAEPHVRomHVszeSnrB2qQBGNHy6BgyZAHwACvxkAAmpxyFT7N37qhVnGmzYE",
    "CAACAgUAAxkBAAEPHVVomHVsuGrU-zEa0X8i1jn_HW7XawAC-BkAArnxwVRFqeVbp2Mn_TYE",
    "CAACAgUAAxkBAAEPHVZomHVsuf3QWObxnD9mavVnmS4XPgACPhgAAqMryVT761H_MmILCjYE",
    "CAACAgUAAxkBAAEPHVdomHVs87jwVjxQjM7k37cUAwnJXQACwxYAAs2CyFRnx4YgWFPZkjYE",
    "CAACAgUAAxkBAAEPHVhomHVsnB4iVT8jr56ZtGPq98KQeQACfRgAAoQAAcBUyVgSjnENUUo2BA",
    "CAACAgUAAxkBAAEPHVlomHVsRWNXE2vkgSYrBU9K-JB9UwACoxcAAi4MyFS0w-gqFTBWQjYE",
    "CAACAgUAAxkBAAEPHVpomHVsfUZT06tR7jgqmHNJA-j5fAACpBgAAuhZyVSaY0y3w0zVLjYE",
    "CAACAgUAAxkBAAEPHVtomHVsqjujca8HBOPQpEvJY-I0WQACZRQAAhX0wFS2YntXBMU6ATYE",
    "CAACAgUAAxkBAAEPHVxomHVsw09_FKmfugTeaqTXrIOMNwACzhQAAlyLwFSL4-96tJu0STYE",
    "CAACAgUAAxkBAAEPHV1omHVsP9aNtLlGJyErPF8yEvuuawAC6RcAAj7DwFSKnv319y6jnTYE",
    "CAACAgUAAxkBAAEPHV5omHVsuz9c3bxncAXOQ6BDzhrTnwACKxwAAm4QwVRdrk0EgrotFjYE",
    "CAACAgUAAxkBAAEPHV9omHVs3df-rmdlDbJFu-MREg5RrwAC5RYAAsCewVSvwTepiO6BlTYE",
    "CAACAgUAAxkBAAEPHWBomHVshaztRlsJ2d3p6qV1TAolvgACChkAAjf9wFSqz_XgZVhTLTYE",
    "CAACAgUAAxkBAAEPHWFomHVsrjl_UqIUYgs8NUKycyXbuQAChRgAApa6wFQoEbjt-4UEUDYE",
    "CAACAgUAAxkBAAEPHWJomHVssUsAAU8BbI1lcPdQ2hJbbrwAAg4YAAI4lchULkVARTsFmjI2BA",
    "CAACAgUAAxkBAAEPHWNomHVs0wFx3n8i8r6TefoJzP_3XAACqRYAAvKvyFQiY8XErd3KFDYE",
    "CAACAgUAAxkBAAEPHWRomHVsXNHMWzXxpKxSrze5yM0kzAACRx4AAt7oyFS3n9YnyqQwCjYE",
    "CAACAgUAAxkBAAEPHWVomHVsQxKxih6IfqUeZ7aQaCXBvAACyBgAAkHPwVT8uW_J5GUHQTYE",
    "CAACAgUAAxkBAAEPHWZomHVsFSeBqaNqm5rWNu8LdszNcAACxhUAAuEtwVQi2t0gazmalDYE",
    "CAACAgUAAxkBAAEPHWdomHVsFOXCOM_DZb1VuGPlXfkY2AAC4RgAAu2CwVSxJETZ5OhUGTYE",
    "CAACAgUAAxkBAAEPHWhomHVsovXP8XqbvEjEB508DTW6VQAC2BcAAoJLwFRRhczsSdgAASg2BA",
    "CAACAgUAAxkBAAEPHWlomHVsNkxBtCovGit7bjWNEV5kTwACFhYAArQ9wFRAwzg1qA0TrTYE",
    "CAACAgUAAxkBAAEPHWpomHVs8vADDgs56H30a5uM2uNvhQACtxcAAj_QQVSXTCvC5zEIPjYE",
    "CAACAgUAAxkBAAEPHWtomHVsS466sNdxHk4lGsza3S_3yQAC9B0AAnZtQFQJYcwEnXCS6DYE",
    "CAACAgUAAxkBAAEPJzFonedaEsY_x_cVxB5i5WHRmYDfZwACdBgAAnTX8VThqO2DUegdyjYE"
]